/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package frequent_topics;

import org.hamcrest.core.Is;
import org.junit.Assert;
import org.junit.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void takesIsZero() {
        List<String> topics = Arrays.asList("topic");
        List<String> phrases = Arrays.asList("this is a topic");
        int take = 0;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertTrue(freq.isEmpty());
    }

    @Test
    public void takesIsNegative() {
        List<String> topics = Arrays.asList("topic");
        List<String> phrases = Arrays.asList("this is a topic");
        int take = -10;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertTrue(freq.isEmpty());
    }

    @Test
    public void topicsAreEmpty() {
        List<String> topics = Collections.emptyList();
        List<String> phrases = Arrays.asList("this is a topic");
        int take = 3;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertTrue(freq.isEmpty());
    }

    @Test
    public void prashesAreEmpty() {
        List<String> topics = Arrays.asList("topic");
        List<String> phrases = Collections.emptyList();
        int take = 3;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertTrue(freq.isEmpty());
    }

    @Test
    public void takesIsGreaterThanPossible() {
        List<String> topics = Arrays.asList("topic");
        List<String> phrases = Arrays.asList("this is a topic");
        int take = 3;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertEquals(freq, Arrays.asList("topic"));
    }

    @Test
    public void noTopicFound() {
        List<String> topics = Arrays.asList("topic");
        List<String> phrases = Arrays.asList("this is a phrase");
        int take = 3;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertTrue(freq.isEmpty());
    }

    @Test
    public void topicConform() {
        List<String> topics = Arrays.asList("topic", "word", "duh", "yey");
        List<String> phrases = Arrays.asList("this is a topic", "topic don't come easy", "topic is awesome",
                "this is a word", "word is useful", "duh");
        int take = 2;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        Assert.assertEquals(freq, Arrays.asList("topic", "word"));
    }
}
