/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package frequent_topics;

import java.util.Arrays;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<String> topics = Arrays.asList("topic", "word", "duh", "yey");
        List<String> phrases = Arrays.asList("this is a topic", "topic don't come easy", "topic is awesome",
                "this is a word", "word is useful", "duh");
        int take = 2;
        List<String> freq = FrequentTopics.frequentTopics(topics, phrases, take);

        System.out.println(freq);
    }
}
