/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arry_rotation;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

import static java.util.stream.Collectors.toList;

public class App {
    public static int[] ZEROS = {0, 0, 0, 0};
    public static int[] SIZE_4 = {1, 2, 3, 4};
    public static  int[] ARR = {3, 8, 9, 7, 6};
    static int K = 3;

    public static void main(String[] args) {

        List<Integer> integers = Arrays.stream(ARR)
                .boxed()
                .collect(toList());
        if (integers.isEmpty()) {
            System.out.println( ARR);
        }
        if (integers.size() == K) {
            System.out.println( ARR);
        }
        if (Collections.frequency(integers, integers.get(0)) == integers.size()) {
            System.out.println(ARR);
        }
        Collections.rotate(integers, 3);

        System.out.println(integers.stream().mapToInt(i->i).toArray());

    }
}
