/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package babaloo;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Set;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class App {
    public static void main(String[] args) {
        int[] A = {0, 1, 0, 1, 1};

        if (A.length > 100000) {System.out.println(-1);}
        LocalDateTime prev = LocalDateTime.now();
        Set<int[]> a = IntStream.range(0, A.length)
                .mapToObj(i ->  IntStream.range(0, A.length)
                        .mapToObj(j -> new int[] {i, j})
                        .collect(Collectors.toList()))
                .flatMap(List::stream)
                .filter(i -> (i[1] > i[0]) && (A[i[0]] != A[i[1]]) && (A[i[0]] == 0))
                .collect(Collectors.toSet());
        LocalDateTime last = LocalDateTime.now();

        Duration duration = Duration.between(prev, last);

        System.out.println(duration.getSeconds() + " seconds");

        a.stream().forEach(i -> System.out.println(String.format("[%d, %d]", i[0], i[1])));
    }
}
