/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binary_gap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App {
    public static final int GAP = 34;

    public static void main(String[] args) {
        Pattern pattern = Pattern.compile("(?!1)(0+)(?=1)");
        Matcher matcher = pattern.matcher(Integer.toBinaryString(GAP));
        int len = 0;

        while (matcher.find()) {
            final String group = matcher.group();
            if (group.length() > len) { len = group.length();}
        }

        System.out.println(len);
    }
}
